spring.application.name=subastas
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/subastas_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#URL del 'productos'
productos-service.url=http://localhost:8082/api/productos